version: '3.8'

services:
  backend_thesis:
    container_name: backend_thesis
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/app