version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - mynet

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mynet

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    networks:
      - mynet
    command: ["mongod", "--bind_ip_all", "--auth"]
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  mynet:
    driver: bridge
